name: Docker

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: fabian
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: ghcr.io/worldskills/api-proxy:latest
