name: Docker

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Docker login
        run: echo "${{ secrets.CONTAINER_REGISTRY_TOKEN }}" | docker login ghcr.io --username fabian --password-stdin

      - name: Build Docker image
        run: docker-compose build api_proxy

      - name: Push image
        run: docker-compose push api_proxy
